package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/hellohirusha/creator-os/graph/model"
	appMiddleware "github.com/hellohirusha/creator-os/internal/middleware"
	"github.com/hellohirusha/creator-os/internal/services"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, storeName string, subdomain string, email string, password string) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Signup - signup"))
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, firstName *string, lastName *string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UpdateProfile - updateProfile"))
}

// CreateProduct creates a new product for the authenticated tenant
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	tenantID := appMiddleware.GetTenantID(ctx)

	p, err := r.ProductService.CreateProduct(ctx, services.CreateProductInput{
		TenantID:    tenantID,
		Name:        input.Name,
		Description: stringValue(input.Description),
		BasePrice:   input.BasePrice,
		Tags:        input.Tags,
	})
	if err != nil {
		return nil, err
	}

	return modelToGraphQL(p), nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id uuid.UUID, input model.UpdateProductInput) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: UpdateProduct - updateProduct"))
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteProduct - deleteProduct"))
}

// PublishProduct sets a product's status to active for the authenticated tenant
func (r *mutationResolver) PublishProduct(ctx context.Context, id uuid.UUID) (*model.Product, error) {
	tenantID := appMiddleware.GetTenantID(ctx)
	if tenantID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	p, err := r.ProductService.PublishProduct(ctx, tenantID, id.String())
	if err != nil {
		return nil, err
	}

	return modelToGraphQL(p), nil
}

// AddProductImage is the resolver for the addProductImage field.
func (r *mutationResolver) AddProductImage(ctx context.Context, productID uuid.UUID, url string, altText *string) (*model.ProductImage, error) {
	panic(fmt.Errorf("not implemented: AddProductImage - addProductImage"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Tenant looks up a store by its subdomain (public storefront entry point)
func (r *queryResolver) Tenant(ctx context.Context, subdomain string) (*model.Tenant, error) {
	var t model.Tenant
	var id string
	err := r.DB.QueryRow(ctx, `
        SELECT id, name, subdomain, plan, is_active, created_at
        FROM tenants
        WHERE subdomain = $1 AND is_active = true
    `, subdomain).Scan(&id, &t.Name, &t.Subdomain, &t.Plan, &t.IsActive, &t.CreatedAt)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// Unknown subdomain — the schema allows a null tenant
			return nil, nil
		}
		return nil, err
	}

	t.ID = parseUUID(id)
	return &t, nil
}

// Products lists the authenticated tenant's products, or — when tenantId is
// given (public storefront) — another tenant's active products only
func (r *queryResolver) Products(ctx context.Context, tenantID *uuid.UUID, status *string) ([]*model.Product, error) {
	tenant := appMiddleware.GetTenantID(ctx)

	statusFilter := ""
	if status != nil {
		statusFilter = *status
	}

	if tenantID != nil {
		// Never expose another tenant's drafts to public callers
		if tenantID.String() != tenant {
			statusFilter = "active"
		}
		tenant = tenantID.String()
	}

	if tenant == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	products, err := r.ProductService.ListProducts(ctx, tenant, statusFilter)
	if err != nil {
		return nil, err
	}

	// Convert models to GraphQL types
	var result []*model.Product
	for _, p := range products {
		result = append(result, modelToGraphQL(p))
	}
	return result, nil
}

// Product fetches a single product (with images and variants) for the tenant
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	tenantID := appMiddleware.GetTenantID(ctx)

	p, err := r.ProductService.GetProduct(ctx, tenantID, id)
	if err != nil {
		return nil, err
	}

	return modelToGraphQL(p), nil
}

// ProductBySlug fetches a product by URL slug for the public storefront
func (r *queryResolver) ProductBySlug(ctx context.Context, tenantID uuid.UUID, slug string) (*model.Product, error) {
	p, err := r.ProductService.GetProductBySlug(ctx, tenantID.String(), slug)
	if err != nil {
		return nil, err
	}

	// Public callers only see active products
	if p.Status != "active" {
		return nil, nil
	}

	return modelToGraphQL(p), nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, status *string) ([]*model.Order, error) {
	panic(fmt.Errorf("not implemented: Orders - orders"))
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id uuid.UUID) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: Order - order"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
