package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/hellohirusha/creator-os/graph/model"
	appMiddleware "github.com/hellohirusha/creator-os/internal/middleware"
	"github.com/hellohirusha/creator-os/internal/services"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, storeName string, subdomain string, email string, password string) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Signup - signup"))
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, firstName *string, lastName *string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UpdateProfile - updateProfile"))
}

// CreateProduct creates a new product for the authenticated tenant
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	tenantID := appMiddleware.GetTenantID(ctx)

	p, err := r.ProductService.CreateProduct(ctx, services.CreateProductInput{
		TenantID:    tenantID,
		Name:        input.Name,
		Description: stringValue(input.Description),
		BasePrice:   input.BasePrice,
		Tags:        input.Tags,
	})
	if err != nil {
		return nil, err
	}

	return modelToGraphQL(p), nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id uuid.UUID, input model.UpdateProductInput) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: UpdateProduct - updateProduct"))
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteProduct - deleteProduct"))
}

// PublishProduct is the resolver for the publishProduct field.
func (r *mutationResolver) PublishProduct(ctx context.Context, id uuid.UUID) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: PublishProduct - publishProduct"))
}

// AddProductImage is the resolver for the addProductImage field.
func (r *mutationResolver) AddProductImage(ctx context.Context, productID uuid.UUID, url string, altText *string) (*model.ProductImage, error) {
	panic(fmt.Errorf("not implemented: AddProductImage - addProductImage"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Tenant is the resolver for the tenant field.
func (r *queryResolver) Tenant(ctx context.Context, subdomain string) (*model.Tenant, error) {
	panic(fmt.Errorf("not implemented: Tenant - tenant"))
}

// Products lists all products for the authenticated tenant
func (r *queryResolver) Products(ctx context.Context, status *string) ([]*model.Product, error) {
	tenantID := appMiddleware.GetTenantID(ctx)

	statusFilter := ""
	if status != nil {
		statusFilter = *status
	}

	products, err := r.ProductService.ListProducts(ctx, tenantID, statusFilter)
	if err != nil {
		return nil, err
	}

	// Convert models to GraphQL types
	var result []*model.Product
	for _, p := range products {
		result = append(result, modelToGraphQL(p))
	}
	return result, nil
}

// Product fetches a single product (with images and variants) for the tenant
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	tenantID := appMiddleware.GetTenantID(ctx)

	p, err := r.ProductService.GetProduct(ctx, tenantID, id)
	if err != nil {
		return nil, err
	}

	return modelToGraphQL(p), nil
}

// ProductBySlug is the resolver for the productBySlug field.
func (r *queryResolver) ProductBySlug(ctx context.Context, tenantID uuid.UUID, slug string) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: ProductBySlug - productBySlug"))
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, status *string) ([]*model.Order, error) {
	panic(fmt.Errorf("not implemented: Orders - orders"))
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id uuid.UUID) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: Order - order"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
